export declare function setClan(target: string): boolean;
export declare function ensureEffect(ef: Effect, turns?: number): void;
export declare function tryEnsureEffect(ef: Effect, turns?: number): boolean;
export declare function getPropertyInt(name: string): number;
export declare function getPropertyBoolean(name: string, default_?: boolean | null): boolean;
export declare function setPropertyInt(name: string, value: number): void;
export declare function useLimitedSkill(prop: string, currSkill: Skill, casts?: number): boolean;
export declare function useLimitedItem(prop: string, currItem: Item, number?: number): boolean;
export declare function farmCastSkill(sk: Skill): void;
export declare function setProps(): void;
export declare function kingFreed(): void;
export declare function dailies(): "Intro already complete!" | "Intro completed.";
export declare function farmPrep(): "Intro completed." | "Farm prep already complete!";
export declare function calculateFarmingTurns(): number;
export declare function fillSpleen(): void;
export declare function runDiet(): void;
export declare function buffUp(): void;
export declare function farmEquipBuilder(meatDrop?: number, ...priorityItems: Item[]): void;
export declare function libramBurn(): void;
export declare function selectFamiliar(loc: Location): Familiar;
export declare function kramcoPercent(): number;
export declare function afterAdventure(): void;
export declare function adventureHere(loc: Location, fam?: Familiar): void;
export declare function freeFights(): "You've finished your free fights" | "Free fights are complete.";
export declare function barfMountain(): void;
export declare function nightCap(): void;
